### ISSUE TITLE
admin_client does not show messages

### ISSUE THREAD

**Issue by 0xtun4** [VDS13/Socketgram-Support-Chat#1]
admin_client does not show messages when press enter or send button.
Is it because user_client's room does not match admin_client's room causing the error?

**Comment by VDS13** [comment]
Hello.
Can you describe the problem in more detail?

**Comment by 0xtun4** [comment]
i use chat folder in admin_client without login. i set
`sessionStorage.setItem("adm_chat", "admin@admin.com");` in admin_client
`$room = "adm12";` in room.php.`
```
sessionStorage.setItem("id", 40);
 sessionStorage.setItem("room", 10); in user_client
```
When sending a message to the user,  chat message does not display that the message has been sent. I have to refresh the page to see what has been sent

**Comment by 0xtun4** [comment]
![image](https://github.com/VDS13/Socketgram-Support-Chat/assets/96949286/1721c6b6-cb45-4e29-b431-5fbbbabcae1b)
user send message
![image](https://github.com/VDS13/Socketgram-Support-Chat/assets/96949286/62bfabd7-fac1-41db-80f4-de4c62fafa57)
admin response
but new message in admin_client not show when receive or send

**Comment by VDS13** [comment]
The logic is written so that the room is formed according to a certain principle:
https://github.com/VDS13/Socketgram-Support-Chat/blob/main/README.md?plain=1#L57

If required, I can show in the code what needs to be changed to introduce a different scheme for forming rooms.

**Comment by 0xtun4** [comment]
Thank you, let me try the code again. If there are any issues, I will respond later.
